"""added_actor_and_directors_2

Revision ID: 08a9904270f1
Revises: ab7992a9e6d3
Create Date: 2023-08-27 13:26:48.422622

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '08a9904270f1'
down_revision = 'ab7992a9e6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_column('directors')
        batch_op.drop_column('actors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actors', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('directors', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
