"""empty message

Revision ID: 2809659c2846
Revises: 5dc3fd68d476
Create Date: 2023-08-21 17:11:36.099101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2809659c2846'
down_revision = '5dc3fd68d476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raiting', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('poster', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_column('poster')
        batch_op.drop_column('description')
        batch_op.drop_column('type')
        batch_op.drop_column('raiting')

    # ### end Alembic commands ###
