"""added_more_field_for_film

Revision ID: 49949c124d10
Revises: 4c316128f909
Create Date: 2023-08-23 17:55:03.370386

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '49949c124d10'
down_revision = '4c316128f909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('movieLength', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ageRating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genres', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
        batch_op.add_column(sa.Column('actors', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
        batch_op.add_column(sa.Column('directors', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
        batch_op.drop_column('raiting')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raiting', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('directors')
        batch_op.drop_column('actors')
        batch_op.drop_column('genres')
        batch_op.drop_column('ageRating')
        batch_op.drop_column('movieLength')
        batch_op.drop_column('year')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
